### PR TITLE
Simplify if condition 

### PR DESCRIPTION
**Pull request by bhawna94**
This PR consists of the following changes:
- Simplify if condition

### CODE REVIEW

**Comment by bhawna94** [comment]
@olamy @epugh @jukka 
I think we can simplify these if conditions.

**Comment by bhawna94** [comment]
@olamy @epugh @jukka 
Could you please review the PR and let me know your thoughts

**Comment by ayushhooda** [comment]
@jochenw It seems to be very much correct. ! Operator is nothing but a shorthand for false condition

**Comment by bhawna94** [comment]
Exactly @ayushhooda 
I am using shorthand here for the false condition.
@jochenw Both the things are identical 
**object instanceof Foo == false**   
and **!(object instanceof Foo)**

**Comment by XenoAmess** [comment]
@bhawna94 Hi. I'm not any official guy of this repo so calling me is pointless...
also, @asfgit is just a robot for sync so calling him is pointless either...
btw I feel neutral about this pr, it looks slightly better than origion, but seems not change anything output.
so I vote +0.5 here.

**Comment by bhawna94** [comment]
@XenoAmess So could you please help me out in knowing the right person who can review the PR.

**Comment by XenoAmess** [comment]
> @XenoAmess So could you please help me out in knowing the right person who can review the PR.

Gilles Sadowski seems the most active official committer in this repo.
But he do not use github...
If you wanna call him you'd better send a mail in the mailing list of commons dev, or create a JIRA ticket for this pr in JIRA https://issues.apache.org/jira/

**Comment by bhawna94** [comment]
Thanks @jochnew do we need other approvals also to merge the PR?

**Comment by bhawna94** [comment]
> Looks good to me. @bhawna94 as Gilles pointed out in the mailing list, these commits can be squashed into a single one, so that it's easier to revert or navigate through these commits should another developer needs to  could you update the PR with that change, please?

Squashed the commit into a single commit.

**Comment by kinow** [comment]
Thanks!

**Comment by bhawna94** [comment]
> Thanks!

Please let me know how many approvals we need to merge this PR.

**Comment by kinow** [comment]
Sorry @bhawna94 I am away from my computer, approved from my mobile. The changes appear to be in source code, and not only for tests. Would you mind creating an issue for this PR, please? I will take care to update changelog and merge it later this week :+1:

**Comment by bhawna94** [comment]
> Sorry @bhawna94 I am away from my computer, approved from my mobile. The changes appear to be in source code, and not only for tests. Would you mind creating an issue for this PR, please? I will take care to update changelog and merge it later this week  (probably tomorrow at lunch break if not too busy, or maybe once I get home)

Any reason for closing this PR? I am not able to reopen it again.

**Comment by XenoAmess** [comment]
@bhawna94
sometimes they close it instead of merge due to some git reason. 
If they close with a commit then the commit might be your commit. this time it is https://github.com/apache/commons-math/commit/0d937abf8ca9878aadc1b4e62e333976e74e8942

**Comment by bhawna94** [comment]
Thanks @XenoAmess for the information. What should i do now? I cant reopen this PR.

**Comment by XenoAmess** [comment]
> Thanks @XenoAmess for the information. What should i do now? I cant reopen this PR.

you needn't. this pr is already merged. lol

**Pull request closed without merging**
