### PR TITLE
MATH-1579: created new clustering module

### PR DESCRIPTION
**Pull request by orionlibs**
[MATH-1579](https://issues.apache.org/jira/browse/MATH-1579) initial commit for modularising the legacy clustering package. Created new clustering module and moved several classes from legacy into it. These classes do not dependent on any library. Dependencies will be added in later commits or PRs as legacy exceptions, statistics, linear algebra and distance classes start moving to the appropriate modules

### CODE REVIEW

**Comment by orionlibs** [comment]
The build failed because i declared in the pom.xml the artifact commons-math-clustering which doesn't exist yet in the repo. I didn't think of that. What do I have to do about it?

**Comment by orionlibs** [comment]
Removed unused dependency

**Comment by aherbert** [comment]
You should add `commons-math-clustering` to the top level pom.xml so it is included in the build reactor, then add it as a dependency to the `commons-math-legacy` module so this module can see the classes that you have moved.

**Comment by orionlibs** [comment]
@aherbert fixed

**Comment by orionlibs** [comment]
fixed checkstyle errors

**Pull request closed without merging**
