### PR TITLE
Implement the MiniBatchKMeansClusterer

### PR DESCRIPTION
**Pull request by chentao106**
Implement the MiniBatchKMeansClusterer and unit test that compare to KMeansPlusPlusClusterer
MiniBatchKMeans is a fast clustering algorithm base on KMeans(Refer to Python sklearn.cluster.MiniBatchKMeans)
Use a partial points in initialize cluster centers, and mini batch in iterations.
It can finish in few seconds when clustering millions of data, and has few differences between KMeans.
See https://www.eecs.tufts.edu/~dsculley/papers/fastkmeans.pdf

### CODE REVIEW

**Comment by aherbert** [comment]
Hi, thanks for the PR.

The usual method for communication is via the developer mailing list (dev@commons.apache.org) or the issue tracking system Jira (https://issues.apache.org/jira/projects/MATH/issues/).

If you could create a ticket on Jira for this then any discussion or progress will be recorded and archived. If you change the PR to start with the prefix ``MATH-NNN:`` where NNN is the ticket number then Jira will link to any comments on the PR.

Alternatively send an email to the developer mailing list with the prefix ``[math]`` with your suggestions for improvements. All the mailing lists are also archived so any discussion on this will be recorded for future reference.

Currently the PR is failing on travis for not having the correct licence header in the files. Can you add the Apache V2 header (assuming that you created the code or obtained it from somewhere with a compatible licence). Then the tests you have added should then be run by travis.

**Comment by chentao106** [comment]
> Hi, thanks for the PR.
> 
> The usual method for communication is via the developer mailing list ([dev@commons.apache.org](mailto:dev@commons.apache.org)) or the issue tracking system Jira (https://issues.apache.org/jira/projects/MATH/issues/).
> 
> If you could create a ticket on Jira for this then any discussion or progress will be recorded and archived. If you change the PR to start with the prefix `MATH-NNN:` where NNN is the ticket number then Jira will link to any comments on the PR.
> 
> Alternatively send an email to the developer mailing list with the prefix `[math]` with your suggestions for improvements. All the mailing lists are also archived so any discussion on this will be recorded for future reference.
> 
> Currently the PR is failing on travis for not having the correct licence header in the files. Can you add the Apache V2 header (assuming that you created the code or obtained it from somewhere with a compatible licence). Then the tests you have added should then be run by travis.

Thanks for your guidance, I will create a JIRA ticket and fix the problem you mentioned above. I have subscribe the dev ML, but I feel it is inconvenient.

**Comment by chentao106** [comment]
JIRA ticket created: https://issues.apache.org/jira/browse/MATH-1509

**Comment by chentao106** [comment]
Shoud I close this pull request?

**Pull request closed without merging**
